config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      post :authorize, :unauthorize, :forbidden, :unforbidden
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :password_alters,     only: [:edit, :update]
  resources :portraits,           only: [:new, :create, :update] 
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,         only: [:edit, :update]
  before_action :valid_user,       only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:danger] = "密码重置链接已经发送至邮箱中!"
      redirect_to root_url
    else
      flash.now[:danger] = "该邮箱未进行注册!"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "密码不能为空!")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "密码已经被成功重置!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "密码重置链接已经过期!"
        redirect_to new_password_reset_url
      end
    end
end

app/views/password_resets/edit.html.erb
  <%= render 'shared/errors' %>
  <%= form_for(@user, url: password_reset_path(params[:id]) ) do |f| %>
    <%= hidden_field_tag :email, @user.email %>  
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">密码</label>
      <div class="col-sm-10">
        <%= f.password_field :password, class: "form-control" %>
      </div>
    </div>
   
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">密码确认</label>
      <div class="col-sm-10">
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label"></label>
      <div class="col-sm-10">
        <%= f.submit "密码重置", class: "btn btn-primary"%>
      </div> 
    </div>
<% end %>

app/views/password_resets/new.html.erb
  <%= form_for(:password_reset, url: password_resets_path) do |f| %>
  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">邮箱</label>
    <div class="col-sm-10">
      <%= f.email_field :email, class: "form-control" %>
    </div>
  </div>
  
  <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-10">
      <%= f.submit "提交邮箱", class: "btn btn-primary"%>
    </div>
  </div>
  <% end %>