config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      post :authorize, :unauthorize, :forbidden, :unforbidden
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :password_alters,     only: [:edit, :update]
  resources :portraits,           only: [:new, :create, :update] 
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token, :old_password, 
                :crop_x, :crop_y, :crop_w, :crop_h

  mount_uploader :avatar, AvatarUploader
  after_update :crop_avatar

  before_save { self.email = email.downcase }
  before_create :create_activation_digest

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255}, uniqueness: { case_sensitive: false }
  validates :email, format: { with: VALID_EMAIL_REGEX }, unless: proc{ |user| user.email.blank? }
  validates :password, length: { minimum: 6 }, allow_nil: true
    
  has_secure_password

  has_many :addresses, -> { where(address_type: Address::AddressType::User).order("id desc") }
  belongs_to :default_address, class_name: :Address, optional: true
  has_many :orders

  def crop_avatar
    avatar.recreate_versions! if crop_x.present?
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end


  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  def should_generate_new_friendly_id?
    name_changed?
  end
  
  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize.to_s
  end

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :update, :edit, :destroy, 
                                   :authorize, :unauthorize,
                                   :avatar_new, :avatar_create, :avatar_update]
  before_action :logged_in_user, only: [:edit, :update, :destroy, :show, :index,
                                        :avatar_create, :avatar_update, :avatar_new]
  before_action :correct_user, only: [:edit, :update,
                                   :avatar_create, :avatar_update, :avatar_new]
  before_action :admin_user, only: [:destroy, :index, :destroy]
  before_action :superadmin_user, only: [:authorize, :unauthorize, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.uuid = session[:user_uuid]
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:danger] = "查看邮箱，进行激活"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @user.slug = nil
    if @user.update_attributes(user_params)
      flash[:success] = "用户更新成功!"
      redirect_to edit_user_path(@user)
    else
      render 'new'
    end
  end

  def index
    @users = User.order("created_at desc").page(params[:page])
  end

  def destroy
    @user.destroy
    flash[:success] = "用户已经被删除!"
    redirect_to users_path
  end

  def authorize
    @user.toggle!(:admin)

    respond_to do |format|
      format.js
    end
  end

  def forbidden
    @user = User.find(params[:user_id])
    @user.toggle!(:forbidden)

    respond_to do |format|
      format.js
    end
  end

  def unforbidden
    @user = User.find(params[:user_id])
    @user.toggle!(:forbidden)

    respond_to do |format|
      format.js
    end
  end

  def unauthorize
    @user.toggle!(:admin)

    respond_to do |format|
      format.js
    end 
  end
  
  private
    def find_user
      @user = User.friendly.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,:portrait, :gender, :description)
    end
end

app/views/users/_articles.html.erb
<div>
  <table class="table table-sm mt-4">
    <% @articles.each do |article| %>
      <tbody>
        <tr>
          <td class="text-left"><small><%= link_to article.category.name, tag_path(article.category), class: "text-secondary" %></small></td>
          <td class="text-secondary"><%= link_to "#{article.title}", article_path(article), class: "text-secondary"%>&nbsp<small><%= article.created_at.strftime("%Y年%m月%d日") %></small></td>
          <td class="text-right text-secondary"><small><%= article.comments_count %>/<%= article.likes_count %></small></td>
        </tr>
      </tbody>
    <% end %>
  </table>
  <%= paginate @articles %>
</div>

app/views/users/_authorize.html.erb
<%= form_for(@user, url: authorize_user_path(@user), method: :post, remote: true) do |f| %>
  <%=f.submit "设为管理员", class: "btn btn-secondary btn-sm" %>
<% end %>

app/views/users/_forbidden.html.erb
<%= form_for(@user, url: forbidden_user_path(@user), method: :post, remote: true) do |f| %>
  <input type="hidden" name="user_id" value="<%= @user.id %>" />
  <%= f.submit "用户禁止", class: "btn btn-secondary btn-sm" %>
<% end %>

app/views/users/_unauthorize.html.erb
<%= form_for(@user, url: unauthorize_user_path(@user), method: :post, remote: true) do |f| %>
  <%=f.submit "取消管理员", class: "btn btn-secondary btn-sm" %>
<% end %>

app/views/users/_unforbidden.html.erb
<%= form_for(@user, url: unforbidden_user_path(@user), method: :post, remote: true) do |f| %>
  <input type="hidden" name="user_id" value="<%= @user.id %>" />
  <%= f.submit "取消禁用", class: "btn btn-secondary btn-sm" %>
<% end %>

app/views/users/_user_edit.html.erb
<div class="col-md-10">
    <div class="card">
      <div class="card-header text-secondary text-center">
        基本信息
      </div>
      <div class="card-body">
        <%= render 'shared/errors' %>
        <%= form_for(@user, url: user_path(@user), method: 'put') do |f| %>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label text-secondary">用户名</label>
          <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label text-secondary">性别</label>
          <div class="col-sm-10">
            <div class="form-check">
              <%= f.radio_button :gender, "male", class: "form-check-input", checked: "checked" %>
              <label class="form-check-label text-secondary">
                美男子
              </label>
            </div>
            <div class="form-check">
              <%= f.radio_button :gender, "female", class: "form-check-input" %>
              <label class="form-check-label text-secondary">
                美少女
              </label>
            </div>
          </div>
        </div>

        <div class="form-group row mb-0">
          <label class="col-sm-2 col-form-label text-secondary">邮箱</label>
          <div class="col-sm-10">
            <%= f.email_field :email, class: "form-control", disabled: "false" %>
          </div>
        </div>
        
        <div class="form-group row mt-0">
          <label class="col-sm-2 col-form-label text-secondary"> </label>
          <div class="col-sm-10">
            <label class="text-secondary"><small><strong>用户注册后邮箱名称不能修改!</strong></small></label>
          </div>
        </div>
        
        <div class="form-group row">
          <label class="col-sm-2 col-form-label text-secondary">个人说明</label>
          <div class="col-sm-10">
            <%= f.text_area :description, class: "form-control" %>
          </div>
        </div> 

        <div class="form-group row">
          <label class="col-sm-2 col-form-label"></label>
          <div class="col-sm-10">
            <%= f.submit "更新资料", class: "btn btn-primary"%>
          </div>
        </div>
        <% end %>
      </div>
    </div>
</div>

app/views/users/_users.html.erb
<div class="col-md-10">
  <div class="card">
    <div class="card-header text-secondary text-center">
      用户列表
    </div>
    <div class="card-body">
      <table class="table table-sm table-hover table-striped">
        <thead>
          <tr class="text-secondary">
            <th>ID</th>
            <th>用户名</th>
            <th>邮箱</th>
            <th class="text-right">查看/编辑/删除</th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr class="text-secondary">
              <td><%= user.id %></td>
              <td>
                <div class="d-flex flex-row">
                  <div>
                    <%= user.name %>
                  </div>
                  <div id="<%= user.id %>-set-admin">
                    <% if user.admin? && user.superadmin? %>
                      <span class="badge badge-primary">超级管理员</span>
                    <% elsif user.admin? && !user.superadmin? %>
                      <span class="badge badge-primary">管理员</span>
                    <% end -%>
                  </div>
                  <div id="<%= user.id %>-forbidden">
                    <% if user.forbidden? %>
                      <span class="badge badge-danger">被禁用</span>
                    <% end -%>
                  </div>
                </div>
              </td>
              <td><%= user.email %></td>
              <td class="text-right">
                <div class="d-flex flex-row justify-content-end">
                  <div class="item-h1">
                    <%= link_to "查看", user_path(user), class: "btn btn-secondary btn-sm" %>&nbsp
                  </div>
                  <% if current_user.admin? && !current_user?(user) && !user.superadmin? %>
                    <% if current_user.admin? && !user.admin? %>
                      <div class="item-h1">
                        <%= link_to "删除", user, method: :delete, data: { confirm: "确定删除该用户?" }, class: "btn btn-secondary btn-sm" %>&nbsp
                      </div> 
                      <div class="item-h1" id="<%= user.id %>-set-forbidden">
                        <% if user.forbidden? %>
                          <%= render 'unforbidden', "@user": user %>
                        <% else %>
                          <%= render 'forbidden', "@user": user %>
                        <% end -%>
                      </div>&nbsp
                    <% else current_user.superadmin? %>
                      <div class="item-h1">
                        <%= link_to "删除", user, method: :delete, data: { confirm: "确定删除该用户?" }, class: "btn btn-secondary btn-sm" %>&nbsp
                      </div>
                      <div class="item-h1" id="<%= user.id %>-set-forbidden">
                        <% if user.forbidden? %>
                          <%= render 'unforbidden', "@user": user %>
                        <% else %>
                          <%= render 'forbidden', "@user": user %>
                        <% end -%>
                      </div>&nbsp
                    <% end -%>
                    <div class="item-h1", id="<%= user.id %>-set-authorize">
                      <% if current_user.superadmin? %>
                        <% if user.admin? && !user.superadmin? %>
                          <%= render 'unauthorize', "@user": user %>
                        <% else !user.admin? && !user.superadmin? %>
                          <%= render 'authorize', "@user": user %>
                        <% end -%>
                      <% end -%>
                    </div>
                  <% end -%>
                </div>
              </td>
            </tr>
          <% end -%>
        </tbody>
      </table>
    </div>
  </div>
</div>
  <%= paginate @users %>

app/views/users/authorize.js.erb
$("#<%= @user.id%>-set-authorize").html("<%= escape_javascript(render('unauthorize')) %>");
$("#<%=@user.id%>-set-admin").html("<span class='badge badge-primary'>管理员</span>")

app/views/users/edit.html.erb
<div class="row">
  <%= render 'shared/left_bar' %>
  <%= render 'user_edit' %>
</div>

app/views/users/forbidden.js.erb
$("#<%=@user.id%>-set-forbidden").html("<%= escape_javascript(render('unforbidden')) %>");
$("#<%=@user.id%>-forbidden").html("<span class='badge badge-danger'>被禁用</span>")

app/views/users/index.html.erb
<div class="row">
  <%= render 'shared/admin_left_bar' %>
  <%= render 'users' %>
</div>

app/views/users/new.html.erb
<%= render 'shared/errors' %>
<%= form_for(@user, url: users_path, method: 'post') do |f| %>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label text-secondary">用户名</label>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  
  <div class="form-group row">
    <label class="col-sm-2 col-form-label text-secondary">性别</label>
    <div class="col-sm-10">
      <div class="form-check">
        <%= f.radio_button :gender, "male", class: "form-check-input", checked: "checked" %>
        <label class="form-check-label text-secondary">
          美男子
        </label>
      </div>
      <div class="form-check">
        <%= f.radio_button :gender, "female", class: "form-check-input" %>
        <label class="form-check-label text-secondary">
          美少女
        </label>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label text-secondary">邮箱</label>
    <div class="col-sm-10">
      <%= f.email_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label text-secondary">密码</label>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label text-secondary">密码确认</label>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-10">
      <%= f.submit "用户注册", class: "btn btn-primary"%>
    </div> 
  </div>
<% end %>

app/views/users/unauthorize.js.erb
$("#<%= @user.id%>-set-authorize").html("<%= escape_javascript(render('authorize')) %>");
$("#<%= @user.id%>-set-admin").html("")

app/views/users/unforbidden.js.erb
$("#<%= @user.id%>-set-forbidden").html("<%= escape_javascript(render('forbidden')) %>");
$("#<%= @user.id%>-forbidden").html("");