config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      post :authorize, :unauthorize, :forbidden, :unforbidden
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :password_alters,     only: [:edit, :update]
  resources :portraits,           only: [:new, :create, :update] 
end

app/views/shared/_errors.html.erb
<% unless @user.errors.blank? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <% @user.errors.messages.values.flatten.each do |error| %>
        <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
      <% end -%>
    </ul>
  </div>
<% end -%>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer" id="bottom">
  <p class="text-right text-secondadry">
    <small class="text-secondary">Created By <a href="https://www.zhengjiajun.com/", class="text-secondary">Jayzen</a></small>
  </p>
</footer>

app/views/shared/_left_bar.html.erb
<div class='col-md-2'>
    <div class="card">
      <div class="card-header text-secondary text-center">
        个人资料设置
      </div>
      <div class="card-body d-flex flex-column row-hl">
        <div class="p-1 item-hl align-self-center">
          <a href="<%= edit_user_path(current_user) %>", class="btn <%= controller_name == 'users' ? 'btn-primary' : 'btn-outline-secondary' %>">
            <i class="fa fa-user fa-fw"></i> 基本信息</a>
        </div>
        <div class="p-1 item-hl align-self-center">
          <a href="<%= edit_password_alter_path(current_user) %>", class="btn <%= controller_name == 'password_alters' ? 'btn-primary' : 'btn-outline-secondary' %>">
            <i class="fa fa-key fa-fw"></i> 修改密码</a>
        </div>
        <div class="p-1 item-hl align-self-center">
          <a href="<%= new_portrait_path %>", class="btn <%= controller_name == 'portraits' ? 'btn-primary' : 'btn-outline-secondary' %>">
            <i class="fa fa-file-image-o fa-fw"></i> 修改头像</a>
        </div>
      </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light mb-3" style="background:  #FFFFFF" id="top">
  <div class="container">
    <%= link_to "Hello World", root_path, class: "navbar-brand text-secondary" %>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <% if logged_in? %>
            <li class="nav-item"></li>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                <% if current_user.avatar.to_s.size == 0 %>
                  <% if current_user.gender == "male" %>
                    <%= image_tag "male.jpeg", size: "25x25", class: "rounded-circle" %>
                  <% else %>
                    <%= image_tag "female.jpg", size: "25x25", class: "rounded-circle" %>
                  <% end %>
                <% else %>
                  <%= image_tag current_user.avatar.large.url, size: "25x25", class: "rounded-circle" %>
                <% end %>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <%= link_to "个人资料设置", edit_user_path(current_user), class: "dropdown-item text-secondary" %>
                <div class="dropdown-divider"></div>
                <%= link_to "退出", logout_path, method: "delete", class: "dropdown-item text-secondary" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item"><%= link_to "注册", signup_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "登录", login_path, class: "nav-link" %></li>
          <% end -%>
        </ul>
      </div>
  </div>
</nav>