config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      post :authorize, :unauthorize, :forbidden, :unforbidden
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :password_alters,     only: [:edit, :update]
  resources :portraits,           only: [:new, :create, :update] 
end

app/controllers/portraits_controller.rb
class PortraitsController < ApplicationController
  before_action :logged_in_user

  def new
    @user = current_user
  end

  def create
    @user = User.find(params[:user_id])
    if params[:portrait].nil? 
      @user.errors.add(:avatar, "必须提交头像!")
      render 'new'
    elsif @user.update_attributes(user_params)
      if params[:portrait][:avatar].present?
        render :crop
      else
        redirect_to portrait_path(current_user.id)
        flash[:success] = "头像上传成功!"
      end
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:user_id])
    if @user.update_attributes(user_params)
      if params[:portrait][:avatar].present?
        render :crop
      else
        flash[:success] = "头像裁剪成功!"
        redirect_to new_portrait_path
      end
    else
      render :new
    end
  end
 

  private
    def user_params
      params.require(:portrait).permit(:avatar, :crop_x, :crop_y, :crop_w, :crop_h)
    end
end

app/views/portraits/_portrait_crop.html.erb
  <div class='col-md-8'>
    <div class="card">
      <div class="card-header text-secondary">
         待裁剪图片
      </div>
      <div class="card-body">
        <%= image_tag @user.avatar_url(:large), id: "cropbox" %>
        <br>
        <%= form_for(:portrait, url: portrait_path(@user), method: :put) do |f| %>
          <% %w[x y w h].each do |attribute| %>
            <%= f.hidden_field "crop_#{attribute}", id: "portrait_crop_#{attribute}" %>
          <% end %>
          <input type="hidden" name="user_id" value="<%= current_user.id %>" />
          <%= f.submit "提交裁剪", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class='col-md-2'>
    <div class="card">
      <div class="card-header text-secondary text-center">
        图片预览
      </div>
      <div class="card-body">
        <div style="width:100px; height:100px; overflow:hidden; margin:auto">
          <%= image_tag @user.avatar.url(:large), id: "preview" %>
        </div>
      </div>
    </div>
  </div>

app/views/portraits/_portrait_new.html.erb
<div class="col-md-8">
  <div class="card">
    <div class="card-header text-secondary">
      提交头像
    </div>
    <div class="card-body">
      <%= render 'shared/errors' %>
      <%= form_for(:portrait, url: portraits_path) do |f| %>
        <div class="form-group row">
          <div class="col-sm-10">
            <div class="d-flex flex-row row-hl">
              <div class="item-hl">
                <a href="#", class="btn btn-sm text-secondary", id="button_trigger" >
                  <i class="fa fa-upload fa-fw"></i>头像上传
                </a>
              </div>
              <div class="item-hl">
                <p class="btn btn-sm text-secondary" id="upload_file"></p>
              </div>
            </div>
            <%= f.file_field :avatar, class: "form-control text-secondary", hidden: true %>
            <input type="hidden" name="user_id" value="<%= current_user.id %>" />
          </div>
        </div>
  
        <div class="form-group row">
          <div class="col-sm-10">
            <%= f.submit "修改头像", class: "btn btn-primary" %>
          </div> 
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class='col-md-2'>
  <div class="card">
    <div class="card-header text-secondary text-center">
      图片预览
    </div>
    <div class="card-body ">
      <div class="text-center">
        <% if @user.avatar.to_s.size == 0 %>
          <% if @user.gender == "male" %>
            <%= image_tag "male.jpeg", size: "100x100" %>
          <% else %>
            <%= image_tag "female.jpg", size: "100x100" %>
          <% end %>
        <% else %>
          <%= image_tag @user.avatar.large.url, size: "100x100" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      var fileSelect = document.getElementById("button_trigger"),
          fileElem = document.getElementById("portrait_avatar");

      fileSelect.addEventListener("click", function (e) {
        if (fileElem) {
          fileElem.click();
        }
        e.preventDefault(); // prevent navigation to "#"
      }, false);
      
      $("#portrait_avatar").change(function(){
        $("#upload_file").text($("#portrait_avatar").val());
      })
    });
  </script>
<% end %>

app/views/portraits/crop.html.erb
<div class="row">
  <%= render 'shared/left_bar' %>
  <%= render 'portrait_crop' %>
</div>

app/views/portraits/new.html.erb
<div class="row">
  <%= render 'shared/left_bar' %>
  <%= render 'portrait_new' %>
</div>